usr/local/openresty-python3/bin/cython
usr/local/openresty-python3/bin/cythonize
usr/local/openresty-python3/bin/cygdb
usr/local/openresty-python3/lib/python3.12/site-packages/Cython-3.0.11-py3.12.egg-info
usr/local/openresty-python3/lib/python3.12/site-packages/Cython/
usr/local/openresty-python3/lib/python3.12/site-packages/cython.py
usr/local/openresty-python3/lib/python3.12/site-packages/pyximport/
usr/local/openresty-python3/lib/python3.12/site-packages/__pycache__/cython.cpython-312*.py*
