#!/bin/bash

PGDATA=/var/postgres/data
PGPREFIX=/usr/local/openresty/postgresql

[ "$(sudo -u postgres ls -A $PGDATA)" ] || sudo -u postgres $PGPREFIX/bin/initdb -E "UTF8" --locale="en_US.UTF-8" $PGDATA
