Name:           perl-Readonly
Version:        2.05
Release:        1%{?dist}
Summary:        Readonly Perl module
License:        Artistic 2.0
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Readonly/
Source0:        http://www.cpan.org/authors/id/S/SA/SANKO/Readonly-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.005
BuildRequires:  perl(Module::Build::Tiny)
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
# Deep Read-only scalar
Readonly::Scalar    $sca => $initial_value; Readonly::Scalar my $sca =>
$initial_value;

%prep
%setup -q -n Readonly-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install --destdir=$RPM_BUILD_ROOT --create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json minil.toml README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jul 07 2020 Yichun Zhang (agentzh) <yichun@openresty.com> 2.05-1
- Specfile autogenerated by cpanspec 1.78.
